<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CaseCompat.Core\CaseCompat.Core.csproj" />
    <ProjectReference Include="..\CaseCompat.Bethesda.Plugins\CaseCompat.Bethesda.Plugins.csproj" />
    <ProjectReference Include="..\CaseCompat.Filesystem.Linux\CaseCompat.Filesystem.Linux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nifly" Version="1.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CaseCompat.Tests" />
  </ItemGroup>

</Project>
