<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CaseCompat.Core\CaseCompat.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.54.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
